## Gantera Blog Config


markdown: kramdown
highlighter: rouge
sass:
  style: compressed

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

## Repo Location
repository: https://github.com/akshmakov/gantera

timezone: America/Los_Angeles


## define 4 default type collections
## journal - World Journal (PC Perspective)
## posts   - Blog Post (DM)
## chars   - Character Logs
## world   - World Information
defaults:
  -
    scope:
      path: "_journal"
      type: "journal"
    values:
      layout: "post"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_chars"
      type: "chars"
    values:
      layout: "page"
  -
    scope:
      path: "_world"
      type: "world"
    values:
      layout: "page"
      
## Collections Defined Here
collections:
  journal:
    permalink: /:collection/session/:month/:day/
    output: true
  world:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /posts/:year/:month/:day/:title/
    output: true
  chars:
    permalink: /characters/:title
    output: true
    

name: Gantera
description: A Pathfinder Game Blog
url: https://akshmakov.github.io/gantera

theme: minima

#twitter:
#username: jekyllrb

#logo: /img/logo-2x.png

#gems:
#- jekyll-avatar
#- jekyll-feed
#- jekyll-mentions
#- jekyll-redirect-from
#- jekyll-seo-tag
#- jekyll-sitemap
#- jemoji

exclude:
  - .gitignore
  - README.md
  - docker-compose.yml