version: '2'
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
      - 35279:35729
      - 3000:3000
      -   80:4000
      